# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, conduit, dataDefault, fastLogger, hjsmin, hspec
, httpConduit, monadControl, monadLogger, shakespeare, text
, waiExtra, waiLogger, warp, yaml, yesod, yesodAuth, yesodCore
, yesodForm, yesodStatic, yesodTest
}:

cabal.mkDerivation (self: {
  pname = "Yenode";
  version = "0.0.0";
  src = ./Yenode;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson conduit dataDefault fastLogger hjsmin httpConduit
    monadControl monadLogger shakespeare text waiExtra waiLogger warp
    yaml yesod yesodAuth yesodCore yesodForm yesodStatic
  ];
  testDepends = [ hspec yesod yesodCore yesodTest ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
